/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Track {
  name: string
  artist: string
  album?: string
  playcount: number
  timestamp?: number
}
export interface AuthResult {
  success: boolean
  message: string
  sessionKey?: string
}
export declare class LastFmEditClient {
  constructor()
  setCredentials(username: string, password: string): void
  testAuth(): Promise<AuthResult>
  getRecentTracks(count: number): Promise<Array<Track>>
  getArtistTracks(artist: string, count: number): Promise<Array<Track>>
  getMockRecentTracks(count: number): Array<Track>
  getMockArtistTracks(artist: string, count: number): Array<Track>
}
