pub mod default_rules;
pub mod edit;
pub mod event_logger;
pub mod events;
pub mod json_logger;
pub mod rewrite;
pub mod rewrite_processor;
pub mod scrub_action_provider;
pub mod track_cache;
pub mod track_provider;

#[cfg(feature = "cli")]
pub mod cli;
pub mod config;
pub mod musicbrainz;
#[cfg(feature = "openai")]
pub mod openai_provider;
pub mod persistence;
pub mod recent_user_manager;
#[cfg(feature = "tokio")]
pub mod scrubber;
pub mod session_manager;
