[bundle]
identifier = "com.scrobble-scrubber"
publisher = "Scrobble Scrubber"
name = "Scrobble Scrubber"

[application]
# App icon for desktop
icon = ["assets/icon.png"]

[web.app]
# HTML title tag content
title = "Scrobble Scrubber"
# Base template
base_path = "./index.html"

[web.resource]
# Include assets directory
asset_dir = "assets"

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]
# Javascript code file (dev-server only)
script = []
