name: Build Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-builds:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos
          - os: windows-latest
            platform: windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run tests
        working-directory: app
        run: nix develop --command cargo test

      - name: Check formatting
        working-directory: app
        run: nix develop --command cargo fmt --all --check

      - name: Run clippy
        working-directory: app
        run: nix develop --command cargo clippy --all-targets --all-features -- -D warnings

      - name: Test build
        working-directory: app
        run: nix develop --command dx build --release --platform ${{ matrix.platform }}

      - name: Test bundle (Linux only for now)
        if: matrix.os == 'ubuntu-latest'
        working-directory: app
        run: |
          # Only test one bundle type to verify the process works
          nix develop --command dx bundle --release --platform linux --package-types deb