name: Build macOS ARM App

on:
  push:
    branches:
      - "test-app-macos-arm"
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos-arm-app:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix (macOS)
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix store (macOS)
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build app bundle (macOS with Nix)
        run: |
          NIXPKGS_ALLOW_UNFREE=1 nix build --impure .#app

      - name: List artifacts
        run: |
          echo "=== MACOS ARM APP ARTIFACTS ==="
          find result -type f | sort
          echo "App bundle location:"
          find result -name "*.app" -type d | head -5

      - name: Upload app packages
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm-app-test
          path: |
            result/**/*.app
          if-no-files-found: error