name: Build Windows App

on:
  push:
    branches:
      - "test-app-windows"
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows-app:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust (Windows)
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust Cache (Windows)
        uses: Swatinem/rust-cache@v2
        with:
          key: windows-app

      - name: Install cargo-binstall (Windows)
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install Dioxus CLI (Windows)
        run: |
          echo "=== BEFORE INSTALLATION ==="
          echo "CARGO_HOME: $env:CARGO_HOME"
          echo "Contents of cargo bin directory before:"
          if (Test-Path "$env:USERPROFILE\.cargo\bin") {
            Get-ChildItem "$env:USERPROFILE\.cargo\bin" | Select-Object Name, Length, LastWriteTime | Format-Table
          } else {
            echo "Cargo bin directory does not exist yet"
          }

          echo "=== DRY RUN ==="
          cargo binstall --dry-run --no-confirm dioxus-cli --verbose

          echo "=== ACTUAL INSTALLATION ==="
          cargo binstall --no-confirm --force dioxus-cli --verbose

          echo "=== AFTER INSTALLATION ==="
          echo "Contents of cargo bin directory after:"
          Get-ChildItem "$env:USERPROFILE\.cargo\bin" | Select-Object Name, Length, LastWriteTime | Format-Table

          echo "Looking for dx executables:"
          Get-ChildItem "$env:USERPROFILE\.cargo\bin" -Filter "dx*" | Format-Table

      - name: Add cargo bin to PATH and verify dx installation
        run: |
          echo "$env:USERPROFILE\.cargo\bin" >> $env:GITHUB_PATH

          echo "=== PATH UPDATE ==="
          echo "Added to PATH: $env:USERPROFILE\.cargo\bin"

          echo "=== SEARCHING FOR DX ==="
          echo "Searching for all dx files in cargo bin:"
          Get-ChildItem "$env:USERPROFILE\.cargo\bin" | Where-Object { $_.Name -like 'dx*' } | Format-Table Name, Length, Extension

          echo "=== VERSION CHECK ==="
          $dxPath = $null
          if (Test-Path "$env:USERPROFILE\.cargo\bin\dx.exe") {
            $dxPath = "$env:USERPROFILE\.cargo\bin\dx.exe"
            echo "Found dx.exe at: $dxPath"
          } elseif (Test-Path "$env:USERPROFILE\.cargo\bin\dx") {
            $dxPath = "$env:USERPROFILE\.cargo\bin\dx"
            echo "Found dx (no extension) at: $dxPath"
          } else {
            echo "ERROR: dx executable not found!"
            echo "Full directory listing:"
            Get-ChildItem "$env:USERPROFILE\.cargo\bin" | Format-Table
            exit 1
          }

          echo "Checking dx version:"
          & $dxPath --version

      - name: Build app bundle (Windows)
        working-directory: app
        run: |
          # Try dx in PATH first, fallback to full path with .exe extension
          try {
            dx bundle --release --platform windows --package-types nsis
          } catch {
            Write-Host "dx not in PATH, trying full path with .exe..."
            if (Test-Path "$env:USERPROFILE\.cargo\bin\dx.exe") {
              & "$env:USERPROFILE\.cargo\bin\dx.exe" bundle --release --platform windows --package-types nsis
            } else {
              & "$env:USERPROFILE\.cargo\bin\dx" bundle --release --platform windows --package-types nsis
            }
          }

      - name: List artifacts
        working-directory: app
        run: |
          echo "=== WINDOWS APP ARTIFACTS ==="
          Get-ChildItem -Path ../target/dx/scrobble-scrubber-app -Recurse -File | Sort-Object Name | Format-Table

      - name: Upload app packages
        uses: actions/upload-artifact@v4
        with:
          name: windows-app-test
          path: |
            target/dx/scrobble-scrubber-app/**/*.exe
            target/dx/scrobble-scrubber-app/**/*.msi
          if-no-files-found: error
