name: Release

on:
  push:
    tags:
      - "v*"
    branches:
      - "release/*"

permissions:
  contents: write
  packages: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build-all-platforms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build Windows bundle
        working-directory: app
        run: |
          nix develop --command dx bundle --release \
            --platform windows \
            --package-types msi

      - name: Build macOS bundle
        working-directory: app
        run: |
          nix develop --command dx bundle --release \
            --platform macos \
            --package-types dmg

      - name: Build Linux bundle
        working-directory: app
        run: |
          nix develop --command dx bundle --release \
            --platform linux \
            --package-types deb

      - name: List all artifacts
        working-directory: app
        run: |
          echo "Generated artifacts by platform:"
          echo "Windows artifacts:"
          find ../target/dx/scrobble-scrubber-app -name "*.msi" | sort
          echo "macOS artifacts:"
          find ../target/dx/scrobble-scrubber-app -name "*.dmg" | sort
          echo "Linux artifacts:"
          find ../target/dx/scrobble-scrubber-app -name "*.deb" | sort
          echo "All release executables:"
          find ../target/dx/scrobble-scrubber-app/release -name "*app*" -type f | sort

      - name: Upload Windows packages
        uses: actions/upload-artifact@v4
        with:
          name: windows-packages
          path: target/dx/scrobble-scrubber-app/bundle/*/bundle/msi/*.msi
          if-no-files-found: error

      - name: Upload macOS packages
        uses: actions/upload-artifact@v4
        with:
          name: macos-packages
          path: target/dx/scrobble-scrubber-app/bundle/*/bundle/dmg/*.dmg
          if-no-files-found: error

      - name: Upload Linux packages
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: |
            target/dx/scrobble-scrubber-app/bundle/*/bundle/deb/*.deb
            target/dx/scrobble-scrubber-app/release/linux/app/scrobble-scrubber-app
          if-no-files-found: error

  create-release:
    needs: build-all-platforms
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets

      - name: Extract version from tag
        id: version
        run: |
          if [[ ${{ github.ref }} =~ refs/tags/v([0-9]+\.[0-9]+\.[0-9]+.*) ]]; then
            echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "version=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Prepare release assets
        run: |
          echo "Downloaded artifacts:"
          find release-assets -type f | sort
          echo "Preparing release assets..."
          mkdir -p release-files

          # Process Windows artifacts
          find release-assets -name "*.msi" | while read file; do
            cp "$file" release-files/
          done

          # Process macOS artifacts
          find release-assets -name "*.dmg" | while read file; do
            cp "$file" release-files/
          done

          # Process Linux artifacts
          find release-assets -name "*.deb" | while read file; do
            cp "$file" release-files/
          done
          find release-assets -name "scrobble-scrubber-app" -type f | while read file; do
            cp "$file" release-files/scrobble-scrubber-app-linux-x86_64
          done

          echo "Release files prepared:"
          ls -la release-files/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Scrobble Scrubber v${{ steps.version.outputs.version }}"
          body: |
            ## Scrobble Scrubber v${{ steps.version.outputs.version }}

            Desktop application for managing and cleaning Last.fm scrobbles with support for rewrite rules, pending edits, and automated processing.

            ### Downloads

            **Windows:**
            - `*.msi` - Windows installer package

            **macOS:**
            - `*.dmg` - macOS disk image installer

            **Linux:**
            - `*.deb` - Debian/Ubuntu package installer
            - `scrobble-scrubber-app-linux-x86_64` - Standalone binary

            ### Installation

            **Windows:**
            Download and run the `.msi` installer.

            **macOS:**
            Download and mount the `.dmg` file, then drag the app to Applications.

            **Debian/Ubuntu:**
            ```bash
            sudo dpkg -i ScrobbleScrubberApp_*.deb
            ```

            **Linux Standalone Binary:**
            ```bash
            chmod +x scrobble-scrubber-app-linux-x86_64
            ./scrobble-scrubber-app-linux-x86_64
            ```

            ### Features
            - System tray integration with dynamic status
            - Automated scrobble processing and cleanup
            - Configurable rewrite rules for track metadata
            - Pending edits management
            - Real-time status monitoring

            ### Cross-Platform Support
            This release provides native builds for Windows, macOS, and Linux platforms.

            Built with Dioxus 0.7 and Rust.
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: release-files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
