name: Release

on:
  push:
    tags:
      - "v*"
    branches:
      - "release/*"
      - "test-app-*"  # Allow testing specific platforms

permissions:
  contents: write
  packages: read

env:
  CARGO_TERM_COLOR: always

jobs:
  trigger-platform-builds:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || contains(github.ref, 'release/')
    steps:
      - name: Trigger platform builds
        run: |
          echo "Platform builds will be triggered automatically by the dedicated workflows"
          echo "Check the following workflows for build status:"
          echo "- Build Linux App"
          echo "- Build Windows App"  
          echo "- Build macOS Intel App"
          echo "- Build macOS ARM App"

  release-instructions:
    needs: trigger-platform-builds
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || contains(github.ref, 'release/')

    steps:
      - name: Release Instructions
        run: |
          echo "## 🚀 App Release Process with Dedicated Workflows"
          echo ""
          echo "This release now uses dedicated platform workflows for better reliability:"
          echo ""
          echo "### Platform Builds:"
          echo "✅ Linux: Build Linux App workflow" 
          echo "✅ Windows: Build Windows App workflow"
          echo "✅ macOS Intel: Build macOS Intel App workflow"
          echo "✅ macOS ARM: Build macOS ARM App workflow"
          echo ""
          echo "### To create a release:"
          echo "1. Check that all platform workflows completed successfully"
          echo "2. Download artifacts from each successful platform build"
          echo "3. Manually create GitHub release with artifacts"
          echo ""
          echo "### Benefits:"
          echo "- Individual platform debugging"
          echo "- Faster iteration on fixes"  
          echo "- No single point of failure"
          echo "- Manual release control"

