name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'release/*'

permissions:
  contents: write
  packages: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build-all-platforms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build Windows bundle
        working-directory: app
        run: |
          nix develop --command dx bundle --release \
            --platform windows \
            --package-types msi

      - name: Build macOS bundle  
        working-directory: app
        run: |
          nix develop --command dx bundle --release \
            --platform macos \
            --package-types dmg

      - name: Build Linux bundle
        working-directory: app
        run: |
          nix develop --command dx bundle --release \
            --platform linux \
            --package-types deb

      - name: List all artifacts
        working-directory: app
        run: |
          echo "All generated artifacts:"
          find ../target/dx/scrobble-scrubber-app -name "*.msi" -o -name "*.dmg" -o -name "*.deb" | sort

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-bundle
          path: target/dx/scrobble-scrubber-app/bundle/*/bundle/msi/*.msi
          if-no-files-found: warn

      - name: Upload macOS artifacts  
        uses: actions/upload-artifact@v4
        with:
          name: macos-bundle
          path: target/dx/scrobble-scrubber-app/bundle/*/bundle/dmg/*.dmg
          if-no-files-found: warn

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-bundle
          path: target/dx/scrobble-scrubber-app/bundle/*/bundle/deb/*.deb
          if-no-files-found: warn

  create-release:
    needs: build-all-platforms
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets

      - name: Extract version from tag
        id: version
        run: |
          if [[ ${{ github.ref }} =~ refs/tags/v([0-9]+\.[0-9]+\.[0-9]+.*) ]]; then
            echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "version=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Flatten artifacts and list
        run: |
          echo "Downloaded artifacts:"
          find release-assets -type f | sort
          echo "Flattening artifacts..."
          mkdir -p flattened-assets
          find release-assets -name "*.msi" -o -name "*.dmg" -o -name "*.deb" | while read file; do
            cp "$file" flattened-assets/
          done
          echo "Flattened release assets:"
          ls -la flattened-assets/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Scrobble Scrubber v${{ steps.version.outputs.version }}"
          body: |
            ## Scrobble Scrubber v${{ steps.version.outputs.version }}

            Cross-platform desktop application for managing Last.fm scrobbles.

            ### Downloads

            **Windows:**
            - `.msi` - Windows Installer package
            - `.exe` - NSIS installer

            **macOS:**
            - `.app` - macOS application bundle
            - `.dmg` - macOS disk image installer

            **Linux:**
            - `.deb` - Debian/Ubuntu package
            - `.AppImage` - Universal Linux application

            ### Installation

            **Windows:** Download and run the `.msi` or `.exe` installer
            **macOS:** Download the `.dmg`, open it, and drag the app to Applications
            **Linux:** 
            - Debian/Ubuntu: `sudo dpkg -i scrobble-scrubber_*.deb`
            - AppImage: `chmod +x *.AppImage && ./ScrobbleScrubber-*.AppImage`
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: flattened-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}